import type { Metadata } from "next";
import { Toaster } from "@/app/components/ui/toaster";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <section>
      {children}

      <Toaster />
    </section>
  );
}
