
export const CourseList = [
  {
    courseId: 1,
    code: "CET 101",
    title: "Introduction to Computer Engineering Technology",
    unit: 3,
    description: "Overview of computer engineering technology, including hardware components, software systems, and career opportunities.",
  },
  {
    courseId: 2,
    code: "CET 102",
    title: "Digital Electronics",
    unit: 4,
    description: "Fundamentals of digital circuits, logic gates, flip-flops, and the design of combinational and sequential systems.",
  },
  {
    courseId: 3,
    code: "CET 201",
    title: "Computer Architecture",
    unit: 3,
    description: "Study of CPU design, memory systems, input/output devices, and instruction set architecture.",
  },
  {
    courseId: 4,
    code: "CET 202",
    title: "Microprocessors and Interfacing",
    unit: 4,
    description: "Architecture, programming, and interfacing of microprocessors and microcontrollers in embedded systems.",
  },
  {
    courseId: 5,
    code: "CET 203",
    title: "Data Communication and Networking",
    unit: 3,
    description: "Principles of data transmission, network topologies, protocols, and basic configuration of networking devices.",
  },
  {
    courseId: 6,
    code: "CET 301",
    title: "Embedded Systems Design",
    unit: 3,
    description: "Design, development, and testing of embedded systems using microcontrollers and real-time operating systems.",
  },
  {
    courseId: 7,
    code: "CET 302",
    title: "Operating Systems",
    unit: 3,
    description: "Concepts and design of operating systems, including process management, memory management, and file systems.",
  },
  {
    courseId: 8,
    code: "CET 303",
    title: "Database Systems",
    unit: 3,
    description: "Design and implementation of relational databases, SQL programming, and data modeling techniques.",
  },
  {
    courseId: 9,
    code: "CET 401",
    title: "Capstone Project in Computer Engineering Technology",
    unit: 4,
    description: "Team-based project integrating hardware and software concepts to solve real-world engineering problems.",
  },
];
